### ISSUE TITLE
外部类的构造方法有办法代理吗？

### ISSUE THREAD

**Issue by WangZhen0908** [Knight-ZXW/LancetX#12]
比如new Intent时

把
**Intent intent1 = new Intent("111");**
替换成
**Log.e("LancetXProxy", "newIntent 调用了", throwable);
Intent intent1 = new Intent("111");**

**下面这种写法会报错：**
    @Proxy
    @TargetMethod(methodName = "<init>")
    @TargetClass(value = "android.content.Intent")
    public void LancetXProxy(String packageName) {
        Throwable throwable = new Throwable();
        Log.e("LancetXProxy", "newIntent 调用了", throwable);
        Origin.callVoid();
    }

2023-02-02 14:50:02.481 14158-14158/com.moon.lancetX.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.moon.lancetX.demo, PID: 14158
    java.lang.VerifyError: Verifier rejected class com.moon.lancetX.demo.MainActivity: void com.moon.lancetX.demo.MainActivity.access$000(android.content.Intent, java.lang.String) failed to verify: void com.moon.lancetX.demo.MainActivity.access$000(android.content.Intent, java.lang.String): [0x0] Expected initialization on uninitialized reference Reference: android.content.Intent
     void com.moon.lancetX.demo.MainActivity.onCreate(android.os.Bundle) failed to verify: void com.moon.lancetX.demo.MainActivity.onCreate(android.os.Bundle): [0x19] register v1 has type Uninitialized Reference: android.content.Intent Allocation PC: 21 but expected Reference: android.content.Intent (declaration of 'com.moon.lancetX.demo.MainActivity' appears in /data/data/com.moon.lancetX.demo/code_cache/.overlay/base.apk/classes.dex)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1287)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4519)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4842)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:113)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2928)
        at android.os.Handler.dispatchMessage(Handler.java:117)
        at android.os.Looper.loopOnce(Looper.java:205)
        at android.os.Looper.loop(Looper.java:293)
        at android.app.ActivityThread.main(ActivityThread.java:9596)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)

**Comment by Knight-ZXW** [comment]
暂未支持  对构造函数调用的 代理

**Comment by Knight-ZXW** [comment]
> > 暂未支持 对构造函数调用的 代理
> 
> 有计划考虑支持下不

我找个时间试下

**Comment by Knight-ZXW** [comment]
> 

针对你的示例 ，可以更新到 0.0.7 版本 ，可以用 @ReplaceNewInvoke， 该注解 表示替换 new xx() 指令，  函数的第一个参数表示 原类型，第二个参数表示替换后的类型.
示例如下
```
    @ReplaceNewInvoke()
    public static void replaceIntent(Intent intent, WrappedIntent newIntent){
    }
```

通过该注解 ，代码中所有调用
Intent a = new Intent()
Intent b =new Intent("aa")
都会被替换为
Intent a = new WrappedIntent ()
Intent b =new WrappedIntent ("aa")
-------------------------------------------

package com.knightboost.lancetx.weaver;

import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.util.Log;

public class WrappedIntent extends Intent {

    public WrappedIntent(Intent o) {
        super(o);
    }

    public WrappedIntent(String action) {
        super(action);
        Throwable throwable = new Throwable();
        Log.e("LancetXProxy", "newIntent 调用了", throwable);
    }

    public WrappedIntent(String action, Uri uri) {
        super(action, uri);
    }

    public WrappedIntent(Context packageContext, Class<?> cls) {
        super(packageContext, cls);
    }

    public WrappedIntent(String action, Uri uri, Context packageContext, Class<?> cls) {
        super(action, uri, packageContext, cls);
    }
}
