### ISSUE TITLE
应是运行不起来，我也不知道啥错了

### ISSUE THREAD

**Issue by Alexxiaopang** [Knight-ZXW/LancetX#17]
INFO [byteX     ] init
INFO [byteX     ] Process init cost time = [7 ms]
INFO [byteX     ] Process loading cache cost time = [8 ms]
ERROR [byteX     ] We found duplicate module-info class files in the project.
ERROR [byteX     ] We found duplicate module-info class files in the project.
ERROR [byteX     ] We found duplicate module-info class files in the project.
ERROR [byteX     ] We found duplicate module-info class files in the project.
ERROR [byteX     ] We found duplicate module-info class files in the project.
ERROR [byteX     ] Failed to read class META-INF/versions/16/com/squareup/moshi/RecordJsonAdapter$ComponentBinding.class
ERROR [byteX     ] We found duplicate module-info class files in the project.
java.lang.UnsupportedOperationException: Records requires ASM8
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:112)
	at com.ss.android.ugc.bytex.common.visitor.GenerateGraphClassVisitor.visit(GenerateGraphClassVisitor.java:31)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at com.ss.android.ugc.bytex.common.visitor.ClassVisitorChain.accept(ClassVisitorChain.java:55)
	at com.ss.android.ugc.bytex.common.processor.ClassFileAnalyzer.handle(ClassFileAnalyzer.java:107)
	at com.ss.android.ugc.bytex.transformer.processor.ClassFileProcessor.process(ClassFileProcessor.java:27)
	at com.ss.android.ugc.bytex.transformer.processor.ProcessorChain.proceed(ProcessorChain.java:30)
	at com.ss.android.ugc.bytex.transformer.processor.FilterFileProcessor.process(FilterFileProcessor.java:23)
	at com.ss.android.ugc.bytex.transformer.processor.ProcessorChain.proceed(ProcessorChain.java:30)
	at com.ss.android.ugc.bytex.transformer.processor.task.TraverseTask.compute(TraverseTask.java:31)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:396)
	at java.base/java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:853)
	at com.ss.android.ugc.bytex.transformer.processor.task.FileTraverseTask.compute(FileTraverseTask.java:40)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
ERROR [byteX     ] We found duplicate module-info class files in the project.
ERROR [byteX     ] Failed to read class META-INF/versions/16/com/squareup/moshi/RecordJsonAdapter.class
java.lang.UnsupportedOperationException: NestMember requires ASM7
	at org.objectweb.asm.ClassVisitor.visitNestMember(ClassVisitor.java:251)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:696)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at com.ss.android.ugc.bytex.common.visitor.ClassVisitorChain.accept(ClassVisitorChain.java:55)
	at com.ss.android.ugc.bytex.common.processor.ClassFileAnalyzer.handle(ClassFileAnalyzer.java:107)
	at com.ss.android.ugc.bytex.transformer.processor.ClassFileProcessor.process(ClassFileProcessor.java:27)
	at com.ss.android.ugc.bytex.transformer.processor.ProcessorChain.proceed(ProcessorChain.java:30)
	at com.ss.android.ugc.bytex.transformer.processor.FilterFileProcessor.process(FilterFileProcessor.java:23)
	at com.ss.android.ugc.bytex.transformer.processor.ProcessorChain.proceed(ProcessorChain.java:30)
	at com.ss.android.ugc.bytex.transformer.processor.task.TraverseTask.compute(TraverseTask.java:31)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
ERROR [byteX     ] Failed to read class META-INF/versions/16/com/squareup/moshi/RecordJsonAdapter$1.class
java.lang.UnsupportedOperationException: NestHost requires ASM7
	at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:165)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:586)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at com.ss.android.ugc.bytex.common.visitor.ClassVisitorChain.accept(ClassVisitorChain.java:55)
	at com.ss.android.ugc.bytex.common.processor.ClassFileAnalyzer.handle(ClassFileAnalyzer.java:107)
	at com.ss.android.ugc.bytex.transformer.processor.ClassFileProcessor.process(ClassFileProcessor.java:27)
	at com.ss.android.ugc.bytex.transformer.processor.ProcessorChain.proceed(ProcessorChain.java:30)
	at com.ss.android.ugc.bytex.transformer.processor.FilterFileProcessor.process(FilterFileProcessor.java:23)
	at com.ss.android.ugc.bytex.transformer.processor.ProcessorChain.proceed(ProcessorChain.java:30)
	at com.ss.android.ugc.bytex.transformer.processor.task.TraverseTask.compute(TraverseTask.java:31)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by Knight-ZXW** [comment]
应该是字节码兼容问题， 你用的moshi 库 是哪个版本的

**Comment by Alexxiaopang** [comment]
> 应该是字节码兼容问题， 你用的moshi 库 是哪个版本的

1.14.0和1.13.0都试了，都不行，冲突了么？

**Comment by Knight-ZXW** [comment]
这应该是 byteX 默认的ASM版本的问题，

你可以通过 byteX的配置 来支持， 通过修改根工程目录的 gradle.properties ，增加以下配置。
bytex.ASM_API=ASM8
bytex.enableDuplicateClassCheck=false

或者把moshi的库过滤掉。

配置用法详见
https://github.com/bytedance/ByteX/blob/90979d010d5af56e44566a12b827f1f46a38bd4f/wiki/ByteX-Developer-API-zh.md

**Comment by Alexxiaopang** [comment]
> 这应该是 byteX 默认的ASM版本的问题，
> 
> 你可以通过 byteX的配置 来支持， 通过修改根工程目录的 gradle.properties ，增加以下配置。 bytex.ASM_API=ASM8 bytex.enableDuplicateClassCheck=false
> 
> 或者把moshi的库过滤掉。
> 
> 配置用法详见 https://github.com/bytedance/ByteX/blob/90979d010d5af56e44566a12b827f1f46a38bd4f/wiki/ByteX-Developer-API-zh.md

非常感谢，已经可以运行了，但是加了ASM之后，编译时间由之前的一分钟变成了五分钟，这个编译是真的慢啊

**Comment by Knight-ZXW** [comment]
> 

如果你之前项目没有ASM，现在加了ASM 确实对编译时间有较大影响， 不过第二次编译会快一点。

**Comment by Alexxiaopang** [comment]
关于功能性的可以问一下么？我想拦截Calendar.getInstance()按照语法按照以下书写，但是怎么样都没有日志输出，也没拦截成功

@Weaver
public class CalendarProxy {

    @Proxy()
    @TargetClass(value = "android.util.Calendar", scope = Scope.ALL)
    @TargetMethod(methodName = "getInstance")
    public static Calendar replaceGetInstance() {
        Calendar calendar = (Calendar) Origin.call();
        calendar.setFirstDayOfWeek(Calendar.SUNDAY);
        Log.e("拦截了can", "calendar getFirstDayOfWeek" + calendar.getFirstDayOfWeek());
        return calendar;
    }
}

**Comment by Knight-ZXW** [comment]
这是一个静态函数吗？

**Comment by Knight-ZXW** [comment]
这种系统的类，没法直接修改 原类字节码的，我建议直接用 @RepalceInvoke

可以参考：https://github.com/Knight-ZXW/LancetX/blob/main/app/src/main/java/com/knightboost/lancetx/weaver/ReplaceInvokeTest.java

**Comment by Knight-ZXW** [comment]
@ReplaceInvoke(isStatic = true)
    @TargetClass(value = "android.util.Log",scope = Scope.SELF)
    @TargetMethod(methodName = "i")
    public static int replaceLogI2(String tag,String msg){
        msg = msg + "被替换";
        return Log.e("zxw",msg);
    }

**Comment by Alexxiaopang** [comment]
> ```
> @ReplaceInvoke(isStatic = true)
> @TargetClass(value = "android.util.Log",scope = Scope.SELF)
> @TargetMethod(methodName = "i")
> public static int replaceLogI2(String tag,String msg){
>     msg = msg + "被替换";
>     return Log.e("zxw",msg);
> }
> ```

log我拦截都是可以的，只是Calendar 不生效，可能是因为这个类是 抽象的原因，我再看看吧

**Comment by Knight-ZXW** [comment]
@ReplaceInvoke(isStatic = true)
    @TargetClass(value = "java.util.Calendar",scope = Scope.SELF)
    public static Calendar getInstance(){
        Calendar instance = Calendar.getInstance();
         Log.e("CalendarWeave","calender getInstance hook");
         return null;
    }
    
    修改前
    
![image](https://user-images.githubusercontent.com/11730925/233947184-a6d284aa-0507-4d45-b8f7-700e85477d4f.png)

修改后
![image](https://user-images.githubusercontent.com/11730925/233947256-b229cbcd-846b-4527-b00c-3d4c16daf88c.png)

    
![image](https://user-images.githubusercontent.com/11730925/233947152-66e833af-a584-4ae4-8997-430a1860b6a6.png)


目前这个插件不支持增量编译， 你可以clean下工程后 重新试试

**Comment by frankswu** [comment]
> 这应该是 byteX 默认的ASM版本的问题，
> 
> 你可以通过 byteX的配置 来支持， 通过修改根工程目录的 gradle.properties ，增加以下配置。 bytex.ASM_API=ASM8 bytex.enableDuplicateClassCheck=false
> 
> 或者把moshi的库过滤掉。
> 
> 配置用法详见 https://github.com/bytedance/ByteX/blob/90979d010d5af56e44566a12b827f1f46a38bd4f/wiki/ByteX-Developer-API-zh.md

请问 “把moshi的库过滤掉” 是指把依赖中的moshi过滤掉？

**Comment by Knight-ZXW** [comment]
> > 这应该是 byteX 默认的ASM版本的问题，
> > 你可以通过 byteX的配置 来支持， 通过修改根工程目录的 gradle.properties ，增加以下配置。 bytex.ASM_API=ASM8 bytex.enableDuplicateClassCheck=false
> > 或者把moshi的库过滤掉。
> > 配置用法详见 https://github.com/bytedance/ByteX/blob/90979d010d5af56e44566a12b827f1f46a38bd4f/wiki/ByteX-Developer-API-zh.md
> 
> 请问 “把moshi的库过滤掉” 是指把依赖中的moshi过滤掉？


bytex.globalIgnoreClassList 参数可以过滤处理的类，具体看bytex文档
